/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        outline: "#6e7881",
        "primary-container": "#0ea5e9",
        "surface-dim": "#cbdbf5",
        "surface-variant": "#d3e4fe",
        "on-secondary": "#ffffff",
        surface: "#f8f9ff",
        "on-surface-variant": "#3e4850",
        "surface-container": "#e5eeff",
        "primary-fixed-dim": "#89ceff",
        "tertiary-fixed": "#ffdbca",
        "on-secondary-fixed": "#131b2e",
        "on-tertiary-fixed": "#341100",
        "on-tertiary-container": "#592300",
        "tertiary-fixed-dim": "#ffb690",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-high": "#dce9ff",
        "on-background": "#0b1c30",
        "primary-fixed": "#c9e6ff",
        "secondary-container": "#dae2fd",
        "surface-tint": "#006591",
        "secondary-fixed": "#dae2fd",
        "secondary-fixed-dim": "#bec6e0",
        "surface-container-highest": "#d3e4fe",
        "inverse-primary": "#89ceff",
        "tertiary-container": "#fa7417",
        "on-tertiary-fixed-variant": "#783200",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#0b1c30",
        "surface-container-low": "#eff4ff",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#004c6e",
        "on-primary-fixed": "#001e2f",
        "error-container": "#ffdad6",
        secondary: "#565e74",
        "surface-bright": "#f8f9ff",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "on-secondary-container": "#5c647a",
        "on-primary-container": "#003751",
        tertiary: "#9d4300",
        "on-secondary-fixed-variant": "#3f465c",
        primary: "#006591",
        "outline-variant": "#bec8d2",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#213145",
        background: "#f8f9ff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4.5rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "1.5rem",
        "container-max": "1280px",
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-hero": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "title-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-caps": ["'Plus Jakarta Sans'", "sans-serif"],
      },
      fontSize: {
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" }],
        "title-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-xl-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "800" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};
